name: Update README with Recent GitHub Activity

on:
  schedule:
    - cron: "0 * * * *" # every 4 hours
  workflow_dispatch: # allow manual run

permissions:
  contents: write

jobs:
  build:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.7.0
        with:
          CONFIG_FILE: "recent-activity.config.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
